reaction:
  new:
    - ğŸ”´
  clue:
    - ğŸŸ 
  good:
    - ğŸŸ¢
  close:
    - ğŸ¤
  bad:
    - ğŸ‘
    - ğŸ’©
  yes:
    - ğŸ‘
  no:
    - âŒ
thread:
  - title: Deaf Test
    id:
      - dev: 12345
        stage: 12345
        prod: 12345
    group: Deaf Test
    rules: abc
    sticky: abc
