reaction:
  new:
    - ğŸ”´
  clue:
    - ğŸŸ 
  good:
    - ğŸŸ¢
  close:
    - ğŸ¤
  bad:
    - ğŸ‘
    - ğŸ’©
    - poucebasrouge
  yes:
    - correct
    - correct_anim
    - poucehautvert
  no:
    - âŒ
    - Faux
    - Faux_anim
thread:
  - title: Deaf Test
    id:
      - dev: 935625593167441920
        stage: 12345
        prod: 12345
    group: Deaf Test
    sticky: deaf_test
