channel_id:
  - 935625593167441920 #dev
  - 1028052466345988198 #stage
body:
embed:
  title: Deaf Test
  description: "Le but est de trouver le jeu dont est tirÃ© une image (complÃ¨te ou partielle). Celui qui donne la bonne rÃ©ponse devient le nouvau maÃ®tre du jeu.


Le maÃ®tre du jeu anime la partie avec des rÃ©actions sous les messages:

ğŸ”´ dÃ©but du jeu | | :orange_circle: indice supplÃ©mentaire | | ğŸŸ¢ bonne rÃ©ponse

ğŸ‘ :poucebasrouge: ğŸ’© mauvaise rÃ©ponse | | ğŸ¤ on s'approche (bonne sÃ©rie)

En rÃ©ponse Ã  une question: :correct: :correct_anim: :poucehautvert: oui | | âŒ :Faux: :Faux_anim: non"
